language: python
python:
    - 3.6
    - nightly
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - python cigarParse.py
    - python samParse.py
after_success:
    - coveralls