language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt

script:
    #- python cigarParse.py #passes locally, but fails in travis?
    - python samParse.py

notifications:
  email: false
