language: python
python:
    - "3.6"
install:
    - pip install -r parse/requirements.txt
script:
    - python parse/cigarParse.py
    - python parse/samParse.py
    - python tests.py
notifications:
  email: false
